#!/usr/bin/env python
import sys, json, re, base64
from urllib2 import Request, urlopen
print "Content-Type: application/json\n"
ES7_CERN_URL = "https://es-cmssdt.cern.ch:9203"
ES_CERN_URL = "https://es-cmssdt1.cern.ch/es"

def send_error(msg):
  print '{"proxy-error":"%s"}' % msg
  sys.exit()

try:
  data = sys.stdin.read()
  payload = json.loads(data)
  query = payload.pop('query',None)
  method = payload.pop('method','POST')
  es_ser = payload.pop('es_server',ES_CERN_URL)
  if not re.match("^https://es-cms(sdt|)([0-9]+|).cern.ch(:|/).*",es_ser):
    es_ser = ES_CERN_URL
  api_type = payload.pop('api','/_search')
  if not api_type in ["/_search", "/_cat", "/_mapping", "/_template"]: send_error ("Invalid api type: %s" % api_type)
  params = payload.pop('params','')
  index = payload.pop('index','')
  if index:
    if not index.startswith("cmssdt-"): index = 'cmssdt-'+index
    if not re.match('^cmssdt-[*a-zA-Z0-9_/-]+$',index): send_error ("Invalid index name: %s" % index)
  es_user = "cmssdt_ro"
  es_pass = open('/data/secrets/apache-cmssdt-es-secret_ro','r').read().strip()
  prefix = payload.pop('prefix',False)
  if api_type.startswith('/_search'):
    scroll = payload.pop('scroll',0)
    if scroll==1:
      api_type = "/_search?scroll=1m"
    elif scroll>1:
      index = ""
      api_type = "/_search/scroll"
  if api_type == "/_cat": api_type="/_cat/indices"
  if prefix: url = "%s/%s/%s" % (es_ser, api_type, index)
  else: url = "%s/%s%s" % (es_ser, index, api_type)
  if params:
    if '?' in url: url = "%s&%s" % (url, params)
    else: url = "%s?%s" % (url, params)
  header = {"Content-Type": "application/json"}
  header['Authorization'] = 'Basic %s' % base64.b64encode("%s:%s" % (es_user, es_pass))
  try:
    request = Request(url, query, header)
    request.get_method = lambda: method
    print urlopen(request).read()
  except Exception as e:
    send_error("Couldn't send data to elastic search: %s\nurl:%s\nquery:%s" % (str(e),url, query))
except Exception as e:
  send_error("Invalid data, can not read json input.")
