#!/usr/bin/env python
import sys, json, urllib2, re
print "Content-Type: application/json\n"
ES_CERN_URL = "https://es-cmssdt.cern.ch:9203"

def send_error(msg):
  print '{"proxy-error":"%s"}' % msg
  sys.exit()

try:
  data = sys.stdin.read()
  payload = json.loads(data)
  es_ser = payload.pop('es_server',ES_CERN_URL)
  if not re.match("^https://es-cms(sdt|)([0-9]+|).cern.ch(:|/).+",es_ser):
    es_ser = ES_CERN_URL
  api_type = payload.pop('api','/_search')
  if not api_type in ["/_search", "/_cat", "/_mapping", "/_template"]: send_error ("Invalid api type: %s" % api_type)
  index = payload.pop('index','')
  if index:
    if not index.startswith("cmssdt-"): index = 'cmssdt-'+index
    if not re.match('^cmssdt-[*a-zA-Z0-9_/-]+$',index): send_error ("Invalid index name: %s" % index)
  es_user = "cmssdt"
  es_pass = open('/data/secrets/apache-cmssdt-es-secret','r').read().strip()
  prefix = payload.pop('prefix',False)
  if api_type.startswith('/_search'):
    scroll = payload.pop('scroll',0)
    if scroll==1:
      api_type = "/_search?scroll=1m"
    elif scroll>1:
      index = ""
      api_type = "/_search/scroll"
  if api_type == "/_cat": api_type="/_cat/indices"
  if prefix: url = "%s/%s/%s" % (es_ser, api_type, index)
  else: url = "%s/%s%s" % (es_ser, index, api_type)
  passman = urllib2.HTTPPasswordMgrWithDefaultRealm()
  passman.add_password(None, url, es_user, es_pass)
  auth_handler = urllib2.HTTPBasicAuthHandler(passman)
  opener = urllib2.build_opener(auth_handler)
  header = {"Content-Type": "application/json"}
  try:
    urllib2.install_opener(opener)
    if 'query' in payload: request = urllib2.Request(url, payload['query'], header)
    else: request = urllib2.Request(url)
    print urllib2.urlopen(request).read()
  except Exception as e:
    send_error("Couldn't send data to elastic search: %s\nurl:%s\nquery:%s" % (str(e),url, query))
except Exception as e:
  send_error("Invalid data, can not read json input.")

