#!/usr/bin/env python3
print ("Content-Type: text/html\n")

from jenkins_callback import build_jobs
import os , sys , cgi , json , re


data = sys.stdin.read()
try:
  payload = json.loads(data)
except Exception as e:
  print ("Invalid data, can not read json input")
  sys.exit(0)

if (not 'DATA' in payload) or (not re.match('^[a-zA-Z0-9_-]+:[0-9]+$',payload['DATA'])):
  print ("Invalid Data: ",data)
  sys.exit(0)
if (not 'JENKINS_SERVER' in payload) or (not re.match('^http://[a-z][a-z0-9_-]+\.cern\.ch(:[0-9]+|)(/[a-z_-]+|)$',payload['JENKINS_SERVER'])):
  print ("Invalid Data: ",data)
  sys.exit(0)
if (not 'JENKINS_USER' in payload) or (not re.match('^[a-z0-9]+$',payload['JENKINS_USER'])):
  print ("Invalid Data: ",data)
  sys.exit(0)
if ('USER_HEADER' not in payload): payload['USER_HEADER']="ADFS_LOGIN"

xparam = []
henv = 'REMOTE_ADDR'
if 'HTTP_X_FORWARDED_FOR' in os.environ and os.environ['HTTP_X_FORWARDED_FOR']!='': henv = 'HTTP_X_FORWARDED_FOR'
xparam.append({'name':'HOST', 'value': os.environ[henv]})
xparam.append({'name':'DATA', 'value': payload['DATA']})

headers = {payload['USER_HEADER'] : payload['JENKINS_USER']}
build_jobs(payload['JENKINS_SERVER'], [(json.dumps({"parameter":xparam}),"jenkins-webhook")], headers=headers)
